### ISSUE TITLE
Wasn't sure how to contact you!

### ISSUE THREAD

**Issue by Jayshua83** [wriley/FarmSimBackupManager#1]
So since Mogli12 decided to give up on KSM/VCA I was wondering if you had access to older versions of the mod that actually worked on Dedi? I didn't need all the added features anyway and was really just interested in the Adpative steering portion!

Again sorry for putting this here I couldn't find an email or anything!

Josh
Discord | Jayshua#6419
joshmiller83@gmail.com

**Comment by wriley** [comment]
Hi, I sent you a friend request on Discord (Kerbo)
