### ISSUE TITLE
issue  - file download is curpted

### ISSUE THREAD

**Issue by FrogSNS** [wriley/FarmSimBackupManager#3]
hello could u reupload the file when unzipping it … it says file is crypted... I've tried 5 locations on pc.. thanks
hope to get a reply back soon... i also tryed 3 other computers

![Screenshot 2022-03-07 230123](https://user-images.githubusercontent.com/26512098/157163812-a95b2c31-845e-496b-a550-3040fd23d463.png)
![Screenshot 2022-03-07 230147](https://user-images.githubusercontent.com/26512098/157163816-603c9dfd-45ff-41c3-b3a5-38634a26f1ef.png)

**Comment by wriley** [comment]
Hi, thank you for the report. I added a .gitattributes file so github wouldn't break the zip file. They changed something because I've not had to do that before. It should work fine now when you download
